service: xrefs
runtime: custom
env: flex
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 16
liveness_check:
   path: '/liveness_check'
   initial_delay_sec: 600
readiness_check:
  path: '/readiness_check'
  app_start_timeout_sec: 600
