service: buildbot
runtime: custom
env: flex
resources:
  cpu: 12
  memory_gb: 32
  disk_size_gb: 256
manual_scaling:
  instances: 1
readiness_check:
  app_start_timeout_sec: 3600
liveness_check:
  initial_delay_sec: 3600
beta_settings:
  cloud_sql_instances: kythe-repo:us-west1:kythe-buildbot
