steps:
- name: gcr.io/cloud-builders/docker
  id: 'Build image'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/buildkite-agent
  - .
- name: gcr.io/cloud-builders/docker
  id: 'Push image'
  args:
  - push
  - gcr.io/$PROJECT_ID/buildkite-agent
timeout: 1800s # 30 minute timeout
images:
  - gcr.io/$PROJECT_ID/buildkite-agent
